"""Generate concise titles for cloud conversations from cached gen-objs analyses.

The :func:`generate_titles_batch` function is the main entry point — it
chunks a list of ``(conv_id, description)`` items, sends each chunk to
the LLM as a single batch JSON-in / JSON-out call, and falls back to
single-conversation retries when a chunk fails to parse cleanly.

The :func:`description_from_analysis` helper extracts a uniform
"description blob" from any cached :class:`ObjectiveAnalysis` variant
(brief / standard / detailed / *_assess). This is what the LLM sees as
input.

This module is intentionally light-weight — it does not touch the cloud
API, the local DB, or the manifest. Callers handle the apply phase
(see ``ohtv gen titles`` in ``cli.py``).
"""

from __future__ import annotations

import json
import logging
import os
import re
from dataclasses import dataclass, field
from pathlib import Path
from typing import Callable

from ohtv.analysis.objectives import ObjectiveAnalysis

log = logging.getLogger("ohtv")


# =============================================================================
# Constants
# =============================================================================


#: Default LLM-side chunk size — convs per batched JSON-in/JSON-out call.
#: Empirically a good token / accuracy balance: brief descriptions average
#: ~30 tokens each, so 25 fits comfortably inside a 4k input window.
DEFAULT_BATCH_SIZE = 25

#: Maximum title length we accept from the LLM (chars, including a
#: leading emoji and spaces). Enforced post-LLM; offenders trigger a
#: single-conv re-prompt, then a hard truncate fallback.
MAX_TITLE_CHARS = 50

#: Synthesis schema version for title generation (Issue #191).
#: Bump this whenever the prompt or title generation logic changes
#: to invalidate stale cache entries.
SYNTHESIS_SCHEMA_VERSION = "v1"


#: Placeholder titles auto-generated by OpenHands Cloud for unrenamed
#: conversations. The id portion is hex; we accept 5–32 chars to cover
#: both the short 5-char prefix display and the full 32-char id form.
#:
#: Empirical match rate (Issue #89): 13 of 20 most recent unrenamed
#: cloud conversations.
_PLACEHOLDER_TITLE_RE = re.compile(r"^Conversation [0-9a-f]{5,32}$")


# =============================================================================
# Selector predicate
# =============================================================================


def is_placeholder_title(title: str | None) -> bool:
    """Return True when ``title`` is missing or auto-generated.

    The predicate matches:

    * ``None``
    * empty / whitespace-only strings
    * Strings matching ``^Conversation [0-9a-f]{5,32}$`` exactly

    Real titles — even short ones — never match. Trailing or leading
    whitespace around the placeholder pattern is **not** considered a
    placeholder; the cloud API stores the title verbatim and any
    intentional whitespace is treated as user intent.

    Args:
        title: Title string from ``ConversationInfo.title`` or
            ``manifest_entry["title"]``.

    Returns:
        True iff the title is missing or matches the placeholder regex.
    """
    if title is None:
        return True
    if not title.strip():
        return True
    return _PLACEHOLDER_TITLE_RE.match(title) is not None


# =============================================================================
# Description extraction
# =============================================================================


def description_from_analysis(analysis: ObjectiveAnalysis) -> str:
    """Extract a uniform "description blob" from any analysis variant.

    All variants are mapped onto a single short string suitable for the
    LLM titling prompt:

    * **brief** / **brief_assess** — just ``goal``
    * **standard** / **standard_assess** — ``goal`` + each
      ``primary_outcomes`` joined with ``"; "``
    * **detailed** / **detailed_assess** — ``goal`` (if present) +
      ``primary_objectives[*].description`` joined with ``"; "``.
      Sub-objectives are deliberately ignored to keep the LLM prompt
      compact.

    If the analysis carries no meaningful text at all (e.g. only an
    empty ``primary_objectives`` list), the returned string is the
    empty string — callers should treat empty descriptions as a
    cache-miss for titling purposes.

    Args:
        analysis: A cached :class:`ObjectiveAnalysis`.

    Returns:
        A short description string. May be empty if the analysis has
        no usable content.
    """
    detail = analysis.detail_level

    if detail in ("brief", "brief_assess"):
        return (analysis.goal or "").strip()

    if detail in ("standard", "standard_assess"):
        parts: list[str] = []
        if analysis.goal:
            parts.append(analysis.goal.strip())
        for outcome in analysis.primary_outcomes or []:
            if outcome and outcome.strip():
                parts.append(outcome.strip())
        return "; ".join(parts)

    # detailed / detailed_assess (or anything we don't recognise)
    parts = []
    if analysis.goal:
        parts.append(analysis.goal.strip())
    if analysis.summary:
        parts.append(analysis.summary.strip())
    for obj in analysis.primary_objectives or []:
        if obj.description and obj.description.strip():
            parts.append(obj.description.strip())
    return "; ".join(parts)


# =============================================================================
# LLM response parsing
# =============================================================================


def parse_titles_response(response_text: str) -> dict[str, str]:
    """Parse a JSON-array LLM response into a ``{id: title}`` dict.

    The expected response shape is::

        [{"id": "...", "title": "..."}, ...]

    Markdown code fences are tolerated and stripped. Each entry must
    be a dict with non-empty ``id`` and ``title`` string fields;
    malformed entries are silently skipped (the caller decides what to
    do about missing ids).

    Args:
        response_text: Raw text from the LLM completion.

    Returns:
        Mapping ``conversation_id -> title``. Empty if nothing parses.

    Raises:
        ValueError: If the outer JSON does not parse or is not a list.
    """
    text = response_text.strip()

    if text.startswith("```"):
        lines = text.split("\n")
        lines = lines[1:]
        if lines and lines[-1].strip() == "```":
            lines = lines[:-1]
        text = "\n".join(lines).strip()

    try:
        parsed = json.loads(text)
    except json.JSONDecodeError as e:
        raise ValueError(f"LLM response is not valid JSON: {e}") from e

    if not isinstance(parsed, list):
        raise ValueError(
            f"Expected JSON array, got {type(parsed).__name__}: {text[:120]!r}"
        )

    out: dict[str, str] = {}
    for entry in parsed:
        if not isinstance(entry, dict):
            continue
        conv_id = entry.get("id")
        title = entry.get("title")
        if not isinstance(conv_id, str) or not isinstance(title, str):
            continue
        conv_id = conv_id.strip()
        title = title.strip()
        if not conv_id or not title:
            continue
        out[conv_id] = title
    return out


# =============================================================================
# Title post-validation
# =============================================================================


# Tolerance: we accept the model returning a title slightly longer than
# the hard cap (it happens) and truncate without re-prompting up to a
# small overshoot. Past this we re-prompt single-conv to give it a
# chance to do better than a blunt truncation.
_TRUNCATE_OVERSHOOT = 8


def _truncate_title(title: str, limit: int = MAX_TITLE_CHARS) -> str:
    """Hard-truncate a title to ``limit`` characters with an ellipsis.

    The ellipsis (``…``, U+2026) costs 1 character against ``limit``,
    matching how the cloud UI renders truncations.
    """
    if len(title) <= limit:
        return title
    # 1 char for the ellipsis
    return title[: limit - 1].rstrip() + "…"


def _is_acceptable(title: str) -> bool:
    """Return True iff ``title`` already meets the hard length cap."""
    return bool(title) and len(title) <= MAX_TITLE_CHARS


# =============================================================================
# Batch generation
# =============================================================================


@dataclass
class TitleGenerationResult:
    """Result of a batched title-generation pass.

    Attributes:
        titles: Mapping of ``conversation_id -> generated_title``.
            Only ids the LLM actually returned a usable title for.
        missing_ids: Ids that were requested but never received a
            title (LLM omitted them and the single-conv retry also
            failed). Empty in the common case.
        cost: Accumulated LLM cost across all chunk + retry calls.
        chunks_called: Number of LLM calls actually made (batched
            chunks plus any single-conv retries).
    """

    titles: dict[str, str] = field(default_factory=dict)
    missing_ids: list[str] = field(default_factory=list)
    cost: float = 0.0
    chunks_called: int = 0


# Type alias for an LLM completion callable. Tests inject a stub here
# to avoid any dependency on the OpenHands SDK / live network.
#
# The callable takes (system_prompt, user_prompt) and returns
# (response_text, cost_dollars).
LLMCallable = Callable[[str, str], tuple[str, float]]


def _default_llm_callable(model: str | None) -> LLMCallable:
    """Build an LLM callable backed by ``openhands.sdk.LLM``.

    Imported lazily so the rest of the module stays import-cheap and
    tests can stub the call site without dragging the SDK in.
    """
    os.environ.setdefault("OPENHANDS_SUPPRESS_BANNER", "1")

    from openhands.sdk import LLM, Message, TextContent

    base = LLM.load_from_env()
    if model:
        llm = LLM(model=model, api_key=base.api_key, base_url=base.base_url)
    else:
        llm = base

    def _call(system_prompt: str, user_prompt: str) -> tuple[str, float]:
        messages = [
            Message(role="system", content=[TextContent(type="text", text=system_prompt)]),
            Message(role="user", content=[TextContent(type="text", text=user_prompt)]),
        ]
        response = llm.completion(messages)
        text = ""
        for item in response.message.content:
            if hasattr(item, "text"):
                text += item.text
        cost = response.metrics.accumulated_cost
        return text, cost

    return _call


def _chunk(items: list, size: int):
    """Yield successive ``size``-sized chunks of ``items``."""
    if size <= 0:
        raise ValueError(f"batch_size must be > 0, got {size}")
    for i in range(0, len(items), size):
        yield items[i : i + size]


def _format_user_prompt(items: list[tuple[str, str]]) -> str:
    """Wrap ``items`` as the JSON-in/JSON-out user message."""
    payload = [{"id": conv_id, "description": desc} for conv_id, desc in items]
    return (
        "Convert the following conversation descriptions into titles "
        "following the rules above. Respond with JSON only.\n\n"
        f"{json.dumps(payload, ensure_ascii=False, indent=2)}"
    )


def _enforce_length(
    raw_titles: dict[str, str],
    items: list[tuple[str, str]],
    llm_call: LLMCallable,
    system_prompt: str,
) -> tuple[dict[str, str], float, int]:
    """Re-prompt single-conv for any title exceeding the hard length cap.

    Falls back to a blunt truncate-with-ellipsis when the model still
    cannot produce a short-enough title — we never want a batch run to
    fail just because one description is verbose.

    Returns:
        ``(final_titles, extra_cost, extra_chunk_calls)``.
    """
    item_by_id = dict(items)
    final = dict(raw_titles)
    extra_cost = 0.0
    extra_calls = 0

    for conv_id, title in list(raw_titles.items()):
        # Tolerate small overshoots without burning another LLM call.
        if len(title) <= MAX_TITLE_CHARS:
            continue
        if len(title) <= MAX_TITLE_CHARS + _TRUNCATE_OVERSHOOT:
            final[conv_id] = _truncate_title(title)
            log.debug("Truncated overlong title for %s (%d -> %d chars)",
                      conv_id, len(title), len(final[conv_id]))
            continue

        desc = item_by_id.get(conv_id, "")
        log.debug("Re-prompting %s for shorter title (%d chars)", conv_id, len(title))
        single_prompt = _format_user_prompt([(conv_id, desc)])
        extra_calls += 1
        try:
            retry_text, retry_cost = llm_call(system_prompt, single_prompt)
        except Exception as e:
            log.warning("Length-retry LLM call failed for %s: %s", conv_id, e)
            final[conv_id] = _truncate_title(title)
            continue
        extra_cost += retry_cost
        try:
            retry_parsed = parse_titles_response(retry_text)
        except ValueError:
            retry_parsed = {}
        retried_title = retry_parsed.get(conv_id, "").strip()
        if retried_title and _is_acceptable(retried_title):
            final[conv_id] = retried_title
        else:
            # Last resort: hard truncate the original.
            final[conv_id] = _truncate_title(title)
    return final, extra_cost, extra_calls


def generate_titles_batch(
    items: list[tuple[str, str]],
    *,
    model: str | None = None,
    batch_size: int = DEFAULT_BATCH_SIZE,
    llm_call: LLMCallable | None = None,
    system_prompt: str | None = None,
) -> TitleGenerationResult:
    """Generate titles for a list of (conversation_id, description) pairs.

    The items are split into chunks of ``batch_size``; each chunk is
    sent to the LLM as one JSON-array round-trip. If a chunk fails to
    parse cleanly (malformed JSON, wrong shape), each conversation in
    that chunk is retried as a single-item call before being declared
    missing.

    Args:
        items: List of ``(conversation_id, description)`` pairs.
            Descriptions may be empty; the prompt tells the LLM to
            fall back to a generic title in that case.
        model: Optional model override (e.g. ``"haiku"``). When ``None``,
            falls back to ``LLM_MODEL`` from the environment.
        batch_size: Number of items per LLM call. Default
            ``DEFAULT_BATCH_SIZE``.
        llm_call: Optional pre-built LLM callable. Mainly for tests —
            production code passes ``None`` and lets this module build
            one from the environment.
        system_prompt: Optional system-prompt override. When ``None``,
            loads ``prompts/titles/default.md`` (user override at
            ``~/.ohtv/prompts/titles/default.md``).

    Returns:
        A :class:`TitleGenerationResult`.
    """
    if not items:
        return TitleGenerationResult()

    if llm_call is None:
        llm_call = _default_llm_callable(model)
    if system_prompt is None:
        system_prompt = _load_titles_prompt()

    result = TitleGenerationResult()
    item_by_id: dict[str, str] = dict(items)

    for chunk in _chunk(items, batch_size):
        chunk_ids = [conv_id for conv_id, _ in chunk]
        user_prompt = _format_user_prompt(chunk)
        result.chunks_called += 1
        try:
            response_text, cost = llm_call(system_prompt, user_prompt)
        except Exception as e:
            log.warning("LLM call failed for chunk of %d items: %s", len(chunk), e)
            result.missing_ids.extend(chunk_ids)
            continue
        result.cost += cost

        try:
            parsed = parse_titles_response(response_text)
        except ValueError as e:
            log.info(
                "Batch chunk of %d failed to parse (%s); retrying single-conv",
                len(chunk), e,
            )
            parsed = {}

        # Determine which chunk ids were not satisfied by the batch response
        unresolved = [conv_id for conv_id in chunk_ids if conv_id not in parsed]
        result.titles.update({k: v for k, v in parsed.items() if k in item_by_id})

        # Retry each unresolved id one at a time
        for conv_id in unresolved:
            desc = item_by_id.get(conv_id, "")
            single_prompt = _format_user_prompt([(conv_id, desc)])
            result.chunks_called += 1
            try:
                retry_text, retry_cost = llm_call(system_prompt, single_prompt)
            except Exception as e:
                log.warning("Single-conv retry failed for %s: %s", conv_id, e)
                result.missing_ids.append(conv_id)
                continue
            result.cost += retry_cost
            try:
                retry_parsed = parse_titles_response(retry_text)
            except ValueError:
                retry_parsed = {}
            if conv_id in retry_parsed:
                result.titles[conv_id] = retry_parsed[conv_id]
            else:
                result.missing_ids.append(conv_id)

    # Post-validation: enforce hard length cap on any titles the LLM
    # returned. Single-conv length retries happen inside ``_enforce_length``.
    if result.titles:
        adjusted, extra_cost, extra_calls = _enforce_length(
            result.titles, items, llm_call, system_prompt,
        )
        result.titles = adjusted
        result.cost += extra_cost
        result.chunks_called += extra_calls

    return result


# =============================================================================
# Cached title generation
# =============================================================================


@dataclass
class CachedTitleResult:
    """Result of cached title generation.
    
    Attributes:
        titles: Mapping of ``conversation_id -> title``.
        was_cached: Mapping of ``conversation_id -> bool`` indicating
            whether the title was from cache (True) or freshly synthesized (False).
        cost: Accumulated LLM cost for titles that needed synthesis.
        cache_hits: Number of titles served from cache.
        cache_misses: Number of titles that needed synthesis.
        missing_ids: Ids that were requested but never received a title
            (LLM omitted them). Empty in the common case.
    """
    titles: dict[str, str] = field(default_factory=dict)
    was_cached: dict[str, bool] = field(default_factory=dict)
    cost: float = 0.0
    cache_hits: int = 0
    cache_misses: int = 0
    missing_ids: list[str] = field(default_factory=list)


def generate_titles_with_cache(
    conversations: list[tuple[str, str, str]],
    *,
    model: str | None = None,
    force_refresh: bool = False,
    batch_size: int = DEFAULT_BATCH_SIZE,
    llm_call: LLMCallable | None = None,
) -> CachedTitleResult:
    """Generate titles using cache when available.
    
    This function wraps :func:`generate_titles_batch` with synthesis cache
    integration (Issue #191). For each conversation, it checks the
    ``conversation_synthesis`` table for a valid cached title. Only uncached
    conversations are sent to the LLM. Results are automatically stored in
    the cache for future calls.
    
    Cache validation logic:
    
    * Cache hit requires matching ``conversation_updated_at``,
      ``synthesis_version``, and ``synthesis_model``
    * ``--force`` flag bypasses cache entirely
    * New titles are automatically cached with current metadata
    
    Args:
        conversations: List of ``(conversation_id, updated_at, description)``
            tuples. The ``updated_at`` must be from ``conversations.updated_at``
            (ISO 8601 string). The ``description`` should be from
            :func:`description_from_analysis` or equivalent.
        model: Optional model override (e.g. ``"haiku"``). When ``None``,
            falls back to ``LLM_MODEL`` from the environment.
        force_refresh: If True, bypass cache and force re-synthesis.
        batch_size: Number of items per LLM call. Default
            ``DEFAULT_BATCH_SIZE``.
        llm_call: Optional pre-built LLM callable. Mainly for tests —
            production code passes ``None`` and lets the function build
            one from the environment.
    
    Returns:
        A :class:`CachedTitleResult` with titles, cache statistics, and cost.
    
    Examples:
        >>> # Basic usage with cache
        >>> conversations = [
        ...     ("abc123", "2024-01-01T00:00:00Z", "Fix auth bug"),
        ...     ("def456", "2024-01-02T00:00:00Z", "Add new feature"),
        ... ]
        >>> result = generate_titles_with_cache(conversations)
        >>> print(f"Cache hit rate: {result.cache_hits}/{len(conversations)}")
        >>> for conv_id, title in result.titles.items():
        ...     cached = " (cached)" if result.was_cached[conv_id] else ""
        ...     print(f"{conv_id}: {title}{cached}")
    """
    from ohtv.db import get_ready_connection
    from ohtv.db.stores.synthesis_cache_store import SynthesisCacheStore
    
    # Determine effective model name for cache key
    if model:
        effective_model = model
    else:
        effective_model = os.environ.get("LLM_MODEL", "openai/gpt-4o-mini")
    
    result = CachedTitleResult()
    
    with get_ready_connection() as conn:
        store = SynthesisCacheStore(conn)
        
        needs_synthesis: list[tuple[str, str, str]] = []
        
        # Check cache for each conversation
        for conv_id, updated_at, description in conversations:
            if not force_refresh:
                cached_title = store.get_cached_title(
                    conv_id, updated_at, effective_model, SYNTHESIS_SCHEMA_VERSION
                )
                if cached_title:
                    result.titles[conv_id] = cached_title
                    result.was_cached[conv_id] = True
                    result.cache_hits += 1
                    log.debug("Cache hit for %s", conv_id)
                    continue
            
            # Cache miss or force refresh
            needs_synthesis.append((conv_id, updated_at, description))
            result.cache_misses += 1
        
        # Synthesize uncached titles in batch
        if needs_synthesis:
            log.info("Synthesizing %d titles (cache misses)", len(needs_synthesis))
            
            # Extract (id, description) for the batch call
            batch_input = [(cid, desc) for cid, _, desc in needs_synthesis]
            
            gen_result = generate_titles_batch(
                batch_input,
                model=model,
                batch_size=batch_size,
                llm_call=llm_call,
            )
            
            result.cost = gen_result.cost
            result.missing_ids = gen_result.missing_ids
            
            # Cache new results and add to output
            for conv_id, updated_at, _ in needs_synthesis:
                if conv_id in gen_result.titles:
                    title = gen_result.titles[conv_id]
                    result.titles[conv_id] = title
                    result.was_cached[conv_id] = False
                    
                    # Estimate tokens (rough approximation: 1 token ≈ 4 chars)
                    tokens_used = len(title) // 4
                    
                    # Store in cache
                    store.upsert_title(
                        conv_id, updated_at, title, effective_model,
                        SYNTHESIS_SCHEMA_VERSION, tokens_used
                    )
                    log.debug("Cached new title for %s", conv_id)
            
            conn.commit()
    
    return result


# =============================================================================
# Prompt loading
# =============================================================================


def _load_titles_prompt() -> str:
    """Load the titles prompt body, preferring the user override.

    Search order:

    1. ``~/.ohtv/prompts/titles/default.md`` (or ``OHTV_DIR`` override)
    2. Bundled ``src/ohtv/prompts/titles/default.md``

    Returns the prompt body with YAML frontmatter stripped.

    Raises:
        FileNotFoundError: If neither location has the prompt file.
    """
    from ohtv.prompts.discovery import resolve_prompt

    try:
        meta = resolve_prompt("titles", "default")
        return meta.content
    except ValueError:
        # Fall back to direct file read (e.g. discovery cache cleared
        # between tests, or a malformed user override).
        from ohtv.config import get_ohtv_dir

        user_path = get_ohtv_dir() / "prompts" / "titles" / "default.md"
        if user_path.exists():
            text = user_path.read_text()
        else:
            bundled = Path(__file__).parent.parent / "prompts" / "titles" / "default.md"
            text = bundled.read_text()
        # Strip frontmatter if present
        if text.startswith("---\n"):
            parts = text.split("---\n", 2)
            if len(parts) >= 3:
                return parts[2]
        return text


def load_titles_prompt_hash() -> str:
    """Return the 16-hex content hash of the active titles prompt."""
    import hashlib

    return hashlib.sha256(_load_titles_prompt().encode()).hexdigest()[:16]


__all__ = [
    "DEFAULT_BATCH_SIZE",
    "MAX_TITLE_CHARS",
    "SYNTHESIS_SCHEMA_VERSION",
    "CachedTitleResult",
    "LLMCallable",
    "TitleGenerationResult",
    "description_from_analysis",
    "generate_titles_batch",
    "generate_titles_with_cache",
    "is_placeholder_title",
    "load_titles_prompt_hash",
    "parse_titles_response",
]
